on:
  workflow_dispatch

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.TMETZ_TEST }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/tmetz/testpgs/pages/builds"
